# Generated by Django 2.2.9 on 2020-01-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
